"""
resume.py — The Provara Agent Resume Generator

Synthesizes a cryptographic CV from a vault's event stream.
"""

from __future__ import annotations
from typing import Dict, Any, List
from pathlib import Path
from collections import Counter
from datetime import datetime

from .sync_v0 import load_events

def generate_resume(vault_path: Path) -> str:
    """
    Generate a Markdown resume from the vault's verified history.
    """
    events = load_events(vault_path / "events" / "events.ndjson")
    
    # Stats
    total_events = len(events)
    genesis = next((e for e in events if e["type"] == "GENESIS"), None)
    birth_date = genesis["timestamp_utc"][:10] if genesis else "Unknown"
    agent_uid = genesis["payload"]["uid"] if genesis else "Unknown"
    
    # Task Analysis
    tasks = [e for e in events if e.get("payload", {}).get("extension") == "provara.agent.task_v1"]
    task_count = len(tasks)
    success_count = sum(1 for t in tasks if t["payload"]["value"]["status"] == "SUCCESS")
    success_rate = (success_count / task_count * 100) if task_count > 0 else 0.0
    
    # Skills (derived from task tags)
    tags = []
    for t in tasks:
        tags.extend(t["payload"]["value"].get("tags", []))
    top_skills = Counter(tags).most_common(5)
    
    # Performance Attestations
    attestations = [e for e in events if e["type"] == "ATTESTATION"]
    
    # Sub-Agents
    sub_agents = [
        e for e in events 
        if e.get("payload", {}).get("extension") == "provara.agent.lifecycle_v1"
    ]

    # Markdown Build
    md = [
        f"# Provara Verified Resume: {agent_uid}",
        f"",
        f"**Vault Path:** `{vault_path.resolve()}`",
        f"**Born:** {birth_date} • **Events:** {total_events}",
        f"",
        f"## 🏆 Performance",
        f"- **Tasks Completed:** {task_count}",
        f"- **Success Rate:** {success_rate:.1f}%",
        f"- **Attestations:** {len(attestations)} Verified Reviews",
        f"",
        f"## 🛠 Skills",
    ]
    
    if top_skills:
        for tag, count in top_skills:
            md.append(f"- **{tag}**: {count} tasks")
    else:
        md.append("- *No tagged tasks yet*")
        
    md.append("")
    md.append("## 🤖 Sub-Agent Fleet")
    if sub_agents:
        for sa in sub_agents:
            val = sa["payload"]["value"]
            md.append(f"- **{sa['payload']['subject']}** (Spawned {val['created_at_utc'][:10]})")
    else:
        md.append("- *No sub-agents spawned*")
        
    md.append("")
    md.append("## 📜 Recent Activity")
    for e in reversed(events[-5:]):
        ts = e.get("timestamp_utc", "")[:16].replace("T", " ")
        etype = e.get("type")
        subject = e.get("payload", {}).get("subject", "unknown")
        md.append(f"- `{ts}` **{etype}** {subject}")
        
    md.append("")
    md.append("---")
    md.append("*Generated by Provara Protocol v1.0 — Cryptographically Verified*")
    
    return "\n".join(md)
